basePath: /api/v1
definitions:
  models.User:
    properties:
      UserRole:
        type: string
      createTime:
        description: 创建时间
        type: string
      id:
        description: 主键ID
        type: integer
      updatedTime:
        description: 更新时间
        type: string
      userAccount:
        type: string
      userAvatar:
        type: string
      userName:
        type: string
      userPassword:
        type: string
    type: object
  r.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8888
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BI Pro API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: userAccount
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: userPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/models.User'
        "40002":
          description: 参数错误
          schema:
            $ref: '#/definitions/r.Response'
        "40003":
          description: 系统错误
          schema:
            $ref: '#/definitions/r.Response'
      summary: User Login
      tags:
      - UserApi
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: userAccount
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: userPassword
        required: true
        schema:
          type: string
      - description: 检查密码
        in: body
        name: checkPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/models.User'
        "40002":
          description: 参数错误
          schema:
            $ref: '#/definitions/r.Response'
        "40003":
          description: 系统错误
          schema:
            $ref: '#/definitions/r.Response'
      summary: User Register
      tags:
      - UserApi
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
