basePath: /api/v1
definitions:
  r.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  requests.LoginRequest:
    properties:
      userAccount:
        type: string
      userPassword:
        type: string
    type: object
  requests.RegisterRequest:
    properties:
      checkPassword:
        type: string
      userAccount:
        type: string
      userPassword:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8888
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BI Pro API
  version: "1.0"
paths:
  /current:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/r.Response'
        "40005":
          description: 获取当前用户信息失败
          schema:
            $ref: '#/definitions/r.Response'
      summary: Current
      tags:
      - UserApi
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录请求参数
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/requests.LoginRequest'
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/r.Response'
        "40002":
          description: 参数错误
          schema:
            $ref: '#/definitions/r.Response'
        "40003":
          description: 系统错误
          schema:
            $ref: '#/definitions/r.Response'
      summary: User Login
      tags:
      - UserApi
  /logout:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/r.Response'
        "40002":
          description: 参数错误
          schema:
            $ref: '#/definitions/r.Response'
        "40003":
          description: 系统错误
          schema:
            $ref: '#/definitions/r.Response'
      summary: Logout
      tags:
      - UserApi
  /refresh_token:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/r.Response'
        "40005":
          description: 认证失败
          schema:
            $ref: '#/definitions/r.Response'
      summary: RefreshToken
      tags:
      - UserApi
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册请求参数
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterRequest'
      produces:
      - application/json
      responses:
        "0":
          description: 成功
          schema:
            $ref: '#/definitions/r.Response'
        "40002":
          description: 参数错误
          schema:
            $ref: '#/definitions/r.Response'
        "40003":
          description: 系统错误
          schema:
            $ref: '#/definitions/r.Response'
      summary: User Register
      tags:
      - UserApi
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
